language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-aspnet-mvc' ]; then cd .. && eval "mv $currentfolder generator-aspnet-mvc" && cd generator-aspnet-mvc; fi

